services:
  - type: web
    name: trackmail-auth-bridge
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
      - key: PORT
        value: 8001
      - key: SESSION_TTL_SECONDS
        value: 3600
      - key: TOKEN_TTL_SECONDS
        value: 300
