services:
  - type: web
    name: trackmail-backend
    env: python
    plan: free
    buildCommand: "python debug_render.py && pip install -r requirements.txt"
    startCommand: "python app.py"
    envVars:
      - key: SUPABASE_URL
        value: https://fvpggfqkmldgwjbanwyr.supabase.co
      - key: SUPABASE_ANON_KEY
        value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ2cGdnZnFrbWxkZ3dqYmFud3lyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjAyNzY5MjIsImV4cCI6MjA3NTg1MjkyMn0.bqVIUz4t-s6Tc-tmglITDTm1KeY5panOfTKkFzzqTwQ
