services:
  - type: web
    name: trackmail-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python minimal_app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: JWT_AUDIENCE
        value: authenticated
      - key: JWT_ISSUER
        sync: false