/**
 * Mock data for testing the frontend when database is not available
 */

export const mockApplications = [
  {
    id: '1',
    threadId: 'thread-1',
    lastEmailId: 'email-1',
    company: 'Google',
    title: 'Software Engineer',
    jobUrl: 'https://careers.google.com/jobs/123',
    appliedAt: '2024-01-15T10:00:00Z',
    status: 'applied',
    source: 'LinkedIn',
    confidence: 'HIGH',
    atsVendor: 'Greenhouse',
    companyDomain: 'google.com',
    rawSubject: 'Application received for Software Engineer',
    rawSnippet: 'Thank you for your interest in the Software Engineer position...',
    createdAt: '2024-01-15T10:00:00Z',
    updatedAt: '2024-01-15T10:00:00Z',
  },
  {
    id: '2',
    threadId: 'thread-2',
    lastEmailId: 'email-2',
    company: 'Microsoft',
    title: 'Product Manager',
    jobUrl: 'https://careers.microsoft.com/jobs/456',
    appliedAt: '2024-01-14T14:30:00Z',
    status: 'screening',
    source: 'Indeed',
    confidence: 'MEDIUM',
    atsVendor: 'Workday',
    companyDomain: 'microsoft.com',
    rawSubject: 'Application for Product Manager position',
    rawSnippet: 'We have received your application for the Product Manager role...',
    createdAt: '2024-01-14T14:30:00Z',
    updatedAt: '2024-01-14T14:30:00Z',
  },
  {
    id: '3',
    threadId: 'thread-3',
    lastEmailId: 'email-3',
    company: 'Amazon',
    title: 'Data Scientist',
    jobUrl: 'https://amazon.jobs/en/jobs/789',
    appliedAt: '2024-01-13T09:15:00Z',
    status: 'interview',
    source: 'Glassdoor',
    confidence: 'HIGH',
    atsVendor: 'Greenhouse',
    companyDomain: 'amazon.com',
    rawSubject: 'Interview invitation for Data Scientist',
    rawSnippet: 'Congratulations! We would like to invite you for an interview...',
    createdAt: '2024-01-13T09:15:00Z',
    updatedAt: '2024-01-13T09:15:00Z',
  },
  {
    id: '4',
    threadId: 'thread-4',
    lastEmailId: 'email-4',
    company: 'Meta',
    title: 'UX Designer',
    jobUrl: 'https://www.metacareers.com/jobs/101',
    appliedAt: '2024-01-12T16:45:00Z',
    status: 'offer',
    source: 'Email',
    confidence: 'HIGH',
    atsVendor: null,
    companyDomain: 'meta.com',
    rawSubject: 'Job offer for UX Designer position',
    rawSnippet: 'We are pleased to offer you the position of UX Designer...',
    createdAt: '2024-01-12T16:45:00Z',
    updatedAt: '2024-01-12T16:45:00Z',
  },
  {
    id: '5',
    threadId: 'thread-5',
    lastEmailId: 'email-5',
    company: 'Netflix',
    title: 'DevOps Engineer',
    jobUrl: 'https://jobs.netflix.com/jobs/202',
    appliedAt: '2024-01-11T11:20:00Z',
    status: 'rejected',
    source: 'LinkedIn',
    confidence: 'MEDIUM',
    atsVendor: 'Greenhouse',
    companyDomain: 'netflix.com',
    rawSubject: 'Application update for DevOps Engineer',
    rawSnippet: 'Thank you for your interest, but we have decided to move forward...',
    createdAt: '2024-01-11T11:20:00Z',
    updatedAt: '2024-01-11T11:20:00Z',
  },
  {
    id: '6',
    threadId: 'thread-6',
    lastEmailId: 'email-6',
    company: 'Tesla',
    title: 'Full Stack Developer',
    jobUrl: 'https://www.tesla.com/careers/303',
    appliedAt: '2024-01-10T13:00:00Z',
    status: 'interested',
    source: 'Indeed',
    confidence: 'LOW',
    atsVendor: null,
    companyDomain: 'tesla.com',
    rawSubject: 'New job posting: Full Stack Developer',
    rawSnippet: 'We have a new opening for a Full Stack Developer...',
    createdAt: '2024-01-10T13:00:00Z',
    updatedAt: '2024-01-10T13:00:00Z',
  },
  {
    id: '7',
    threadId: 'thread-7',
    lastEmailId: 'email-7',
    company: 'Airbnb',
    title: 'Frontend Engineer',
    jobUrl: 'https://careers.airbnb.com/positions/404',
    appliedAt: '2024-01-09T08:30:00Z',
    status: 'applied',
    source: 'Greenhouse',
    confidence: 'HIGH',
    atsVendor: 'Greenhouse',
    companyDomain: 'airbnb.com',
    rawSubject: 'Application confirmation - Frontend Engineer',
    rawSnippet: 'Your application for the Frontend Engineer position has been received...',
    createdAt: '2024-01-09T08:30:00Z',
    updatedAt: '2024-01-09T08:30:00Z',
  },
  {
    id: '8',
    threadId: 'thread-8',
    lastEmailId: 'email-8',
    company: 'Spotify',
    title: 'Backend Engineer',
    jobUrl: 'https://lifeatspotify.com/jobs/505',
    appliedAt: '2024-01-08T15:45:00Z',
    status: 'screening',
    source: 'Workday',
    confidence: 'MEDIUM',
    atsVendor: 'Workday',
    companyDomain: 'spotify.com',
    rawSubject: 'Application review - Backend Engineer',
    rawSnippet: 'We are currently reviewing applications for the Backend Engineer role...',
    createdAt: '2024-01-08T15:45:00Z',
    updatedAt: '2024-01-08T15:45:00Z',
  },
]

export const mockStats = {
  totalApplications: mockApplications.length,
  thisMonth: 8,
  interviewRate: '33%',
  activeJobs: 12,
}
